# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
    ]
